---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - task
      - dependencies
    groups:
      bundler-patch:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - task
      - dependencies
    cooldown:
      default-days: 3
    groups:
      actions-patch-minor:
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - task
      - dependencies
    cooldown:
      default-days: 3
    groups:
      npm-patch:
        update-types:
          - patch
