source 'https://rubygems.org'

gem 'nanoc', '~> 3.8.0'
gem 'guard-nanoc'
gem 'builder'
gem 'adsf'
gem 'kramdown'
gem 'mime-types'
gem 'nokogiri'
gem 'pygments.rb'
gem 's3_website'
gem 'sass'
gem 'systemu'
